POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL
Cookie: jid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3ZEBtaWFsLmNvbSIsImlkIjoiODlmZTJhMTAtM2ZjNC00MTgxLWE2OWItNTU0MDdiMDg2MWJlIiwiaWF0IjoxNTcyNzA4NzEwLCJleHAiOjE1NzMzMTM1MTB9.v9BO2ipdr8aTssMYGNGCm4yu9hSRyTDF0uIdgdBCQs4

query {
  profile {
    email
    id
    name
    createdDate
  }
}

###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL
Cookie: jid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3ZEBtaWFsLmNvbSIsImlkIjoiODlmZTJhMTAtM2ZjNC00MTgxLWE2OWItNTU0MDdiMDg2MWJlIiwiaWF0IjoxNTcyNzA4NzEwLCJleHAiOjE1NzMzMTM1MTB9.v9BO2ipdr8aTssMYGNGCm4yu9hSRyTDF0uIdgdBCQs4


query{
        papers{
            name
            owner{
                id
                name
                createdDate
            }
            createdDate
        }
}

###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL
Cookie: jid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3ZEBtaWFsLmNvbSIsImlkIjoiODlmZTJhMTAtM2ZjNC00MTgxLWE2OWItNTU0MDdiMDg2MWJlIiwiaWF0IjoxNTcyNjY2NTgzLCJleHAiOjE1NzMyNzEzODN9.XdwDpklHNYtlOPCJ6o6-1Yr-1h-HM-SG21uqGqqKmpI

mutation {
  logout
}


###
POST http://localhost:4000/graphql HTTP/1.1
Content-Type: application/json
X-Request-Type: GraphQL
Cookie: jid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImR3ZEBtaWFsLmNvbSIsImlkIjoiODlmZTJhMTAtM2ZjNC00MTgxLWE2OWItNTU0MDdiMDg2MWJlIiwiaWF0IjoxNTcyNzA4NzEwLCJleHAiOjE1NzMzMTM1MTB9.v9BO2ipdr8aTssMYGNGCm4yu9hSRyTDF0uIdgdBCQs4

mutation {
  createPaper(name:"first paper"){
    name
    owner{
      id
    }
    createdDate
    id
  }
}
